import { Button } from '@mui/material';
import { DataGrid, GridColDef, GridRenderCellParams } from '@mui/x-data-grid';
import BookModel from '../models/BookModel';

export const DataTable: React.FC<{ books: BookModel[] }> = (props) => {
    interface Data {
        id: number;
        name: string;
        publishing_year: number;
        description: string;
        price: number;
        inventory_number: number;
        page_number: number;
        status: string;
        language: string;
        author: string;
        category: string;
        publisher: string;
        weight: number;
        ratings_star: number;
        size: string;
        created_at: string;
        updated_at: string;
        images: any;
        coupon_codes: string;
    }

    function createData(
        id: number,
        name: string,
        publishing_year: number,
        description: string,
        price: number,
        inventory_number: number,
        page_number: number,
        status: string,
        language: string,
        author: string,
        category: string,
        publisher: string,
        weight: number,
        ratings_star: number,
        size: string,
        created_at: string,
        updated_at: string,
        images: any,
        coupon_codes: string,
    ): Data {
        return {
            id,
            name,
            publishing_year,
            description,
            price,
            inventory_number,
            page_number,
            status,
            language,
            author,
            category,
            publisher,
            weight,
            ratings_star,
            size,
            created_at,
            updated_at,
            images,
            coupon_codes,
        };
    }
    const rows = [
        createData(
            1,
            'Book 1',
            2021,
            'Description 1',
            15.99,
            20,
            300,
            'Available',
            'English',
            'Author 1',
            'Category 1',
            'Publisher 1',
            1.5,
            4.5,
            '15x21 cm',
            '2023-01-01',
            '2023-01-02',
            'image1.jpg',
            'CODE1',
        ),
        createData(
            2,
            'Book 2',
            2020,
            'Description 2',
            25.99,
            15,
            200,
            'Out of Stock',
            'French',
            'Author 2',
            'Category 2',
            'Publisher 2',
            1.3,
            4.0,
            '16x22 cm',
            '2023-01-03',
            '2023-01-04',
            'image2.jpg',
            'CODE2',
        ),
        createData(
            3,
            'Book 3',
            2019,
            'Description 3',
            35.99,
            10,
            150,
            'Available',
            'Spanish',
            'Author 3',
            'Category 3',
            'Publisher 3',
            1.2,
            3.5,
            '14x20 cm',
            '2023-01-05',
            '2023-01-06',
            'image3.jpg',
            'CODE3',
        ),
        createData(
            4,
            'Book 4',
            2018,
            'Description 4',
            45.99,
            5,
            100,
            'Available',
            'German',
            'Author 4',
            'Category 4',
            'Publisher 4',
            1.1,
            3.0,
            '13x19 cm',
            '2023-01-07',
            '2023-01-08',
            'image4.jpg',
            'CODE4',
        ),
        createData(
            5,
            'Book 5',
            2017,
            'Description 5',
            55.99,
            25,
            250,
            'Out of Stock',
            'Japanese',
            'Author 5',
            'Category 5',
            'Publisher 5',
            1.4,
            2.5,
            '17x23 cm',
            '2023-01-09',
            '2023-01-10',
            'image5.jpg',
            'CODE5',
        ),
        createData(
            6,
            'Book 6',
            2016,
            'Description 6',
            65.99,
            30,
            350,
            'Available',
            'Chinese',
            'Author 6',
            'Category 6',
            'Publisher 6',
            1.6,
            5.0,
            '18x24 cm',
            '2023-01-11',
            '2023-01-12',
            'image6.jpg',
            'CODE6',
        ),
        createData(
            7,
            'Book 7',
            2015,
            'Description 7',
            75.99,
            18,
            450,
            'Out of Stock',
            'Russian',
            'Author 7',
            'Category 7',
            'Publisher 7',
            1.7,
            4.8,
            '19x25 cm',
            '2023-01-13',
            '2023-01-14',
            'image7.jpg',
            'CODE7',
        ),
        createData(
            8,
            'Book 8',
            2014,
            'Description 8',
            85.99,
            22,
            550,
            'Available',
            'Korean',
            'Author 8',
            'Category 8',
            'Publisher 8',
            1.8,
            4.6,
            '20x26 cm',
            '2023-01-15',
            '2023-01-16',
            'image8.jpg',
            'CODE8',
        ),
        createData(
            9,
            'Book 9',
            2013,
            'Description 9',
            95.99,
            12,
            650,
            'Available',
            'Vietnamese',
            'Author 9',
            'Category 9',
            'Publisher 9',
            1.9,
            4.4,
            '21x27 cm',
            '2023-01-17',
            '2023-01-18',
            'image9.jpg',
            'CODE9',
        ),
        createData(
            10,
            'Book 10',
            2012,
            'Description 10',
            105.99,
            8,
            750,
            'Out of Stock',
            'Thai',
            'Author 10',
            'Category 10',
            'Publisher 10',
            2.0,
            4.2,
            '22x28 cm',
            '2023-01-19',
            '2023-01-20',
            'image10.jpg',
            'CODE10',
        ),
        createData(
            11,
            'Book 11',
            2011,
            'Description 11',
            115.99,
            10,
            800,
            'Available',
            'Italian',
            'Author 11',
            'Category 11',
            'Publisher 11',
            2.1,
            4.0,
            '23x29 cm',
            '2023-01-21',
            '2023-01-22',
            'image11.jpg',
            'CODE11',
        ),
        createData(
            12,
            'Book 12',
            2010,
            'Description 12',
            125.99,
            9,
            850,
            'Out of Stock',
            'Dutch',
            'Author 12',
            'Category 12',
            'Publisher 12',
            2.2,
            3.8,
            '24x30 cm',
            '2023-01-23',
            '2023-01-24',
            'image12.jpg',
            'CODE12',
        ),
        createData(
            13,
            'Book 13',
            2009,
            'Description 13',
            135.99,
            7,
            900,
            'Available',
            'Portuguese',
            'Author 13',
            'Category 13',
            'Publisher 13',
            2.3,
            3.6,
            '25x31 cm',
            '2023-01-25',
            '2023-01-26',
            'image13.jpg',
            'CODE13',
        ),
        createData(
            14,
            'Book 14',
            2008,
            'Description 14',
            145.99,
            6,
            950,
            'Available',
            'Swedish',
            'Author 14',
            'Category 14',
            'Publisher 14',
            2.4,
            3.4,
            '26x32 cm',
            '2023-01-27',
            '2023-01-28',
            'image14.jpg',
            'CODE14',
        ),
        createData(
            15,
            'Book 15',
            2007,
            'Description 15',
            155.99,
            11,
            1000,
            'Out of Stock',
            'Norwegian',
            'Author 15',
            'Category 15',
            'Publisher 15',
            2.5,
            3.2,
            '27x33 cm',
            '2023-01-29',
            '2023-01-30',
            'image15.jpg',
            'CODE15',
        ),
        createData(
            16,
            'Book 16',
            2006,
            'Description 16',
            165.99,
            14,
            1050,
            'Available',
            'Danish',
            'Author 16',
            'Category 16',
            'Publisher 16',
            2.6,
            3.0,
            '28x34 cm',
            '2023-01-31',
            '2023-02-01',
            'image16.jpg',
            'CODE16',
        ),
        createData(
            17,
            'Book 17',
            2005,
            'Description 17',
            175.99,
            13,
            1100,
            'Available',
            'Finnish',
            'Author 17',
            'Category 17',
            'Publisher 17',
            2.7,
            4.9,
            '29x35 cm',
            '2023-02-02',
            '2023-02-03',
            'image17.jpg',
            'CODE17',
        ),
        createData(
            18,
            'Book 18',
            2004,
            'Description 18',
            185.99,
            4,
            1150,
            'Out of Stock',
            'Greek',
            'Author 18',
            'Category 18',
            'Publisher 18',
            2.8,
            4.8,
            '30x36 cm',
            '2023-02-04',
            '2023-02-05',
            'image18.jpg',
            'CODE18',
        ),
        createData(
            19,
            'Book 19',
            2003,
            'Description 19',
            195.99,
            2,
            1200,
            'Available',
            'Turkish',
            'Author 19',
            'Category 19',
            'Publisher 19',
            2.9,
            4.7,
            '31x37 cm',
            '2023-02-06',
            '2023-02-07',
            'image19.jpg',
            'CODE19',
        ),
        createData(
            20,
            'Book 20',
            2002,
            'Description 20',
            205.99,
            1,
            1250,
            'Available',
            'Polish',
            'Author 20',
            'Category 20',
            'Publisher 20',
            3.0,
            4.6,
            '32x38 cm',
            '2023-02-08',
            '2023-02-09',
            'image20.jpg',
            'CODE20',
        ),
    ];

    const columns: GridColDef[] = [
        { field: 'id', headerName: 'ID', width: 70 },
        { field: 'name', headerName: 'Tên', width: 130 },
        { field: 'publishing_year', headerName: 'Năm phát hành', width: 130 },
        { field: 'price', headerName: 'Giá', width: 130 },
        { field: 'inventory_number', headerName: 'Số lượng', width: 130 },
        { field: 'page_number', headerName: 'Số trang', width: 130 },
        { field: 'status', headerName: 'Trạng thái', width: 130 },
        { field: 'language', headerName: 'Ngôn ngữ', width: 130 },
        { field: 'author', headerName: 'Tác giả', width: 130 },
        { field: 'category', headerName: 'Danh mục', width: 130 },
        { field: 'publisher', headerName: 'Nhà XB', width: 130 },
        { field: 'created_at', headerName: 'Ngày tạo', width: 130 },
        { field: 'updated_at', headerName: 'Ngày sửa', width: 130 },
        { field: 'weight', headerName: 'Khối lượng(kg)', width: 130 },
        { field: 'ratings_star', headerName: 'Đánh giá', width: 130 },
        { field: 'size', headerName: 'Kích thước', width: 130 },
        { field: 'images', headerName: 'Ảnh', width: 130 },
        { field: 'coupon_codes', headerName: 'Giảm giá', width: 130 },
        {
            field: 'actions',
            headerName: 'Actions',
            width: 150,
            renderCell: (params: GridRenderCellParams) => (
                <div>
                    <Button
                        variant="contained"
                        color="primary"
                        size="small"
                        onClick={() => handleEdit(params.row)}
                        style={{ marginRight: 8 }}
                    >
                        Edit
                    </Button>
                    <Button
                        variant="contained"
                        color="secondary"
                        size="small"
                        onClick={() => handleDelete(params.row.id)}
                    >
                        Delete
                    </Button>
                </div>
            ),
        },
    ];

    const handleEdit = (row: any) => {
        console.log('Edit row:', row);
        // Thêm logic sửa
    };

    const handleDelete = (id: number) => {
        console.log('Delete row with id:', id);
        // Thêm logic xóa
    };
    return (
        <div style={{ maxHeight: 500, maxWidth: 800 }}>
            <DataGrid
                scrollbarSize={800}
                rows={rows}
                columns={columns}
                initialState={{
                    pagination: {
                        paginationModel: { page: 0, pageSize: 5 },
                    },
                }}
                pageSizeOptions={[5, 10]}
                checkboxSelection
            />
        </div>
    );
};
